import { Product } from "./constants";

export const LAPTOP: Product[] = [

  {
    slug: "ADVAN SOULMATE X ATHLON",
    name: "LAPTOP ADVAN SOULMATE X ATHLON",
    category: "Laptop",
    price: "Rp 7.400.000",
    specs: ["Core i5-1235U", "8GB RAM", "512GB SSD", "14\" FHD"],
    image: "/AdvanAnyar.svg",
    processor: {
      name: "Intel Core i5-1235U",
      brand: "Intel",
      generation: "12th Gen (Alder Lake)",
      cores: "10 (2P+8E)",
      threads: "12",
      baseClock: "1.3 GHz",
      turboClock: "4.4 GHz",
      cache: "12 MB",
      tdp: "15W",
      igpu: "Intel Iris Xe Graphics (80EU)",
    },
  },
  {
    slug: "lenovo-loq-gaming",
    name: "Laptop Lenovo LOQ Gaming",
    category: "Laptop",
    price: "Rp 15.950.000",
    specs: ["Core i7-13650HX", "RTX 4050 6GB", "16GB RAM", "512GB SSD"],
    badge: "Terlaris",
    image: "/LAPTOP LOQ 15ARP10E.svg",
    processor: {
      name: "Intel Core i7-13650HX",
      brand: "Intel",
      generation: "13th Gen (Raptor Lake HX)",
      cores: "14 (6P+8E)",
      threads: "20",
      baseClock: "2.6 GHz",
      turboClock: "4.9 GHz",
      cache: "24 MB",
      tdp: "55W (s.d. 157W turbo)",
      igpu: "Intel UHD Graphics",
    },
  },
  {
    slug: "acer-aspire-lite",
    name: "Laptop Acer Aspire GO AG14",
    category: "Laptop",
    price: "Rp 10.599.000",
    specs: ["Core 5-120U", "16GB RAM", "512GB SSD", "14\" WUXGA", "WINDOWS 11 + OHS"],
    image: "/AcerAspireGOAG14.svg",
    processor: {
      name: "Intel Core 5 120U",
      brand: "Intel",
      generation: "Core Series 1 (Raptor Lake-U Refresh)",
      cores: "10 (2P+8E)",
      threads: "12",
      baseClock: "1.4 GHz",
      turboClock: "5.0 GHz",
      cache: "12 MB",
      tdp: "15W",
      igpu: "Intel Iris Xe Graphics (80EU)",
    },
  },
];